 on:
   push:
     branches:
       - master

 jobs:
   deploy:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout Repository
         uses: actions/checkout@v2

       - name: Install OpenJDK 17
         with:
           java-version: 17

       - name: Build and Package Application
         run: ./mvnw clean package

       - name: Transfer JAR to EC2
         uses: appleboy/scp-action@master
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: 22
           source: "target/cicd_pipeline.jar"
           target: "/home/ubuntu/"

       - name: SSH into EC2 and Restart Application
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: 22
           script: |
             # Stop the application running on port 8080
             sudo lsof -t -i:8080 | xargs -r kill -9
             
             # Run the JAR file in the background
             nohup java -jar /home/ubuntu/cicd_pipeline.jar > /dev/null 2>&1 &
